### ISSUE TITLE
Can't delete characters 

### ISSUE THREAD

**Issue by antoine1619** [SimonDaNinja/youtube_rss#3]
When searching for a video or channel, delete/backspace doesn't work.

**Comment by antoine1619** [comment]
also occurs when typing in numbers for the menu selections

**Comment by SimonDaNinja** [comment]
Hmm... it works on my machine, but I think this problem is because the way I get user input in curses is super hacky, and I'm pretty sure there is a standardized, much much better, way of doing it.

Thanks for letting me know, this'll be the next thing I get on fixing for sure (unfortunately I have a few other stability issues I've noticed myself since I started experimenting with threads that I need to attend to first)

**Comment by SimonDaNinja** [comment]
@toylatte Could you try to pull and see if it works now?

**Comment by canisli** [comment]
It works now, thanks.

**Comment by antoine1619** [comment]
It works now, thanks
